BlueBud/Areas/Identity/Pages/Account/AccessDenied.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BlueBud.Areas.Identity.Pages.Account
{
    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    public class AccessDeniedModel : PageModel
    {
        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public void OnGet()
        {
        }
    }
}

BlueBud/Areas/Identity/Pages/Account/ConfirmEmail.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using BlueBud.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;

namespace BlueBud.Areas.Identity.Pages.Account
{
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<ApplicationDbContext.BlueBudUser> _userManager;

        public ConfirmEmailModel(UserManager<ApplicationDbContext.BlueBudUser> userManager)
        {
            _userManager = userManager;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [TempData]
        public string StatusMessage { get; set; }
        public async Task<IActionResult> OnGetAsync(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return RedirectToPage("/Index");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{userId}'.");
            }

            code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));
            var result = await _userManager.ConfirmEmailAsync(user, code);
            StatusMessage = result.Succeeded ? "Thank you for confirming your email." : "Error confirming your email.";
            return Page();
        }
    }
}

BlueBud/Areas/Identity/Pages/Account/ConfirmEmailChange.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using BlueBud.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;

namespace BlueBud.Areas.Identity.Pages.Account
{
    public class ConfirmEmailChangeModel : PageModel
    {
        private readonly UserManager<ApplicationDbContext.BlueBudUser> _userManager;
        private readonly SignInManager<ApplicationDbContext.BlueBudUser> _signInManager;

        public ConfirmEmailChangeModel(UserManager<ApplicationDbContext.BlueBudUser> userManager, SignInManager<ApplicationDbContext.BlueBudUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [TempData]
        public string StatusMessage { get; set; }

        public async Task<IActionResult> OnGetAsync(string userId, string email, string code)
        {
            if (userId == null || email == null || code == null)
            {
                return RedirectToPage("/Index");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{userId}'.");
            }

            code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));
            var result = await _userManager.ChangeEmailAsync(user, email, code);
            if (!result.Succeeded)
            {
                StatusMessage = "Error changing email.";
                return Page();
            }

            // In our UI email and user name are one and the same, so when we update the email
            // we need to update the user name.
            var setUserNameResult = await _userManager.SetUserNameAsync(user, email);
            if (!setUserNameResult.Succeeded)
            {
                StatusMessage = "Error changing user name.";
                return Page();
            }

            await _signInManager.RefreshSignInAsync(user);
            StatusMessage = "Thank you for confirming your email change.";
            return Page();
        }
    }
}

BlueBud/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.ComponentModel.DataAnnotations;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using BlueBud.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;

namespace BlueBud.Areas.Identity.Pages.Account
{
    public class ForgotPasswordModel : PageModel
    {
        private readonly UserManager<ApplicationDbContext.BlueBudUser> _userManager;
        private readonly IEmailSender _emailSender;

        public ForgotPasswordModel(UserManager<ApplicationDbContext.BlueBudUser> userManager, IEmailSender emailSender)
        {
            _userManager = userManager;
            _emailSender = emailSender;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [BindProperty]
        public InputModel Input { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public class InputModel
        {
            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(Input.Email);
                if (user == null || !(await _userManager.IsEmailConfirmedAsync(user)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return RedirectToPage("./ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please
                // visit https://go.microsoft.com/fwlink/?LinkID=532713
                var code = await _userManager.GeneratePasswordResetTokenAsync(user);
                code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                var callbackUrl = Url.Page(
                    "/Account/ResetPassword",
                    pageHandler: null,
                    values: new { area = "Identity", code },
                    protocol: Request.Scheme);

                await _emailSender.SendEmailAsync(
                    Input.Email,
                    "Reset Password",
                    $"Please reset your password by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

                return RedirectToPage("./ForgotPasswordConfirmation");
            }

            return Page();
        }
    }
}

BlueBud/Areas/Identity/Pages/Account/ForgotPasswordConfirmation.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BlueBud.Areas.Identity.Pages.Account
{
    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    [AllowAnonymous]
    public class ForgotPasswordConfirmation : PageModel
    {
        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public void OnGet()
        {
        }
    }
}

BlueBud/Controllers/ChargerLocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlueBud.Data;
using BlueBud.Models;
using Microsoft.Data.SqlClient;

namespace BlueBud.Controllers
{
    public class ChargerLocationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ChargerLocationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ChargerLocations
        public IActionResult AddFavorite(int id)
        {
          
            var charger = _context.ChargerLocation.Find(id);
            if (charger != null && charger.Favorite == "")
            {
                charger.Favorite = User.Identity.Name;
                _context.SaveChanges();
            }
            else
            {
                return Json(new { error = "Someone else favorite this charger before you" });
            }

            return RedirectToAction("Index", "Home");
        }  
        
        public IActionResult RemoveFav(int id)
        {

            var charger = _context.ChargerLocation.Find(id);
            charger.Favorite = "";
            if (charger != null)
            {
                _context.SaveChanges();
            }
            else
            {
                return Json(new{showPopup = true});

            }

            return RedirectToAction("Index", "Home");
        }  
        
        
        
        public IActionResult Reserve(int id)
        {




            var charger = _context.ChargerLocation.Find(id);
            charger.ChargerRenter = User.Identity.Name;
            if (charger != null)
            {
               
                charger.OccupationStatus = 1;
                _context.SaveChanges();
            }

            return RedirectToAction("Index", "Home");
        }    
        
        public IActionResult ReserveCancel(int id)
        {
            
            var charger = _context.ChargerLocation.Find(id);
            if (charger != null)
            {
                charger.ChargerRenter = "";
                charger.OccupationStatus = 0;
                _context.SaveChanges();
            }

            return RedirectToAction("Index", "Home");
        }   
        
        public async Task<IActionResult> Index()
        {
              return _context.ChargerLocation != null ? 
                          View(await _context.ChargerLocation.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.ChargerLocation'  is null.");
        }

        // GET: ChargerLocations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ChargerLocation == null)
            {
                return NotFound();
            }

            var chargerLocations = await _context.ChargerLocation
                .FirstOrDefaultAsync(m => m.Id == id);
            if (chargerLocations == null)
            {
                return NotFound();
            }

            return View(chargerLocations);
        }

        // GET: ChargerLocations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ChargerLocations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ChargerName,Latitude,Longitude,OccupationStatus,ChargerType")] ChargerLocations chargerLocations)
        {
            if (ModelState.IsValid)
            {
                _context.Add(chargerLocations);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(chargerLocations);
        }

        // GET: ChargerLocations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ChargerLocation == null)
            {
                return NotFound();
            }

            var chargerLocations = await _context.ChargerLocation.FindAsync(id);
            if (chargerLocations == null)
            {
                return NotFound();
            }
            return View(chargerLocations);
        }

        // POST: ChargerLocations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ChargerName,Latitude,Longitude,OccupationStatus,ChargerType")] ChargerLocations chargerLocations)
        {
            if (id != chargerLocations.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(chargerLocations);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChargerLocationsExists(chargerLocations.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(chargerLocations);
        }

        // GET: ChargerLocations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ChargerLocation == null)
            {
                return NotFound();
            }

            var chargerLocations = await _context.ChargerLocation
                .FirstOrDefaultAsync(m => m.Id == id);
            if (chargerLocations == null)
            {
                return NotFound();
            }

            return View(chargerLocations);
        }

        // POST: ChargerLocations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ChargerLocation == null)
            {
                return Problem("Entity set 'ApplicationDbContext.ChargerLocation'  is null.");
            }
            var chargerLocations = await _context.ChargerLocation.FindAsync(id);
            if (chargerLocations != null)
            {
                _context.ChargerLocation.Remove(chargerLocations);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChargerLocationsExists(int id)
        {
          return (_context.ChargerLocation?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

BlueBud/Views/Home/Account.cshtml
@{
    ViewData["Title"] = "Your Account";
}

@model BlueBud.Data.ApplicationDbContext.BlueBudUser;
<h1>@ViewData["Title"]</h1>


<div class="row"> <div class="col-md-6">
        <h3> Profile Page </h3>
        <br></br>
        
        <button  class="w-50 btn btn-lg btn-primary">Save your car</button>
        
        
    </div>


    <div class="row" class="col-md-6">
        
        
    </div>
    
</div>

BlueBud/Views/Home/Favorites.cshtml
@{
    ViewBag.Title = "Reservastion";
    Layout = "_Layout";
}

@{
    ViewData["Title"] = "Home Page";
}

@inject Microsoft.Extensions.Configuration.IConfiguration Configuration





<div class="row"> <div class="col-md-6">
        <h3> Your favorite Blue Buddies </h3>
        @using BlueBud.Data        
        @using Microsoft.AspNetCore.Identity
        @model List<ChargerLocations>
 
        <ul>
            
           
           
            
                @foreach (var charger in Model)
                {
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">@charger.ChargerName</h5>
                            <h6 class="card-subtitle mb-2 text-muted">@charger.ChargerType</h6>
                            <a asp-controller="ChargerLocations" asp-action="RemoveFav" asp-route-id="@charger.Id"> <button id="updatebutton" type="button" class="btn btn-danger">Remove From Favorites</button></a>

                        </div>
                    </div>
                } 
            
            
        </ul>
        
    </div>



        
        
</div>

BlueBud/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@inject Microsoft.Extensions.Configuration.IConfiguration Configuration


@{
    ViewData["Title"] = "Home Page";
}



<div class="row"> <div class="col-md-6">
        <h3> The avaliable Blue Buds </h3>
        @using BlueBud.Data        
        @using Microsoft.AspNetCore.Identity
        @model List<ChargerLocations>
        <ul>
            @foreach (var charger in Model)
            {
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">@charger.ChargerName</h5>
                        <h6 class="card-subtitle mb-2 text-muted">@charger.ChargerType</h6>
                        <a asp-controller="ChargerLocations"  asp-action="Reserve" asp-route-id="@charger.Id" > <button id="updatebutton" type="button" class="btn btn-success">Reserve</button></a>
                        
                        @if (charger.Favorite != User.Identity.Name)
                        {<a asp-controller="ChargerLocations"  asp-action="AddFavorite" asp-route-id="@charger.Id" > <button id="updatebutton" type="button" class="btn btn-success">Add to Favorites</button></a>
                           
                        } 
                        
                    </div>
                </div>
            }
        </ul>
        
    </div>


    <div class="col-md-6" id="map" style="width: 400px; height:600px;">
        
        
    </div>
    
</div>



<script src = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBxinbaf5oXt9Jjy_gpqbXbsPfI-fQBztY" async defer></script>
<script src = "path/to/map.js"></script>

BlueBud/Views/Home/Reservations.cshtml
@{
    ViewBag.Title = "Reservastion";
    Layout = "_Layout";
}

@{
    ViewData["Title"] = "Home Page";
}

@inject Microsoft.Extensions.Configuration.IConfiguration Configuration





<div class="row"> <div class="col-md-6">
        <h3> The reserved Blue Buds </h3>
        @using BlueBud.Data        
@using Microsoft.AspNetCore.Identity
@model List<ChargerLocations>
 
        <ul>
            
            
            @foreach (var charger in Model)
            {
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">@charger.ChargerName</h5>
                        <h6 class="card-subtitle mb-2 text-muted">@charger.ChargerType</h6>
                        <a asp-controller="ChargerLocations" asp-action="ReserveCancel" asp-route-id="@charger.Id"> <button id="updatebutton" type="button" class="btn btn-danger">Cancel Reservation</button></a>
 @if (charger.Favorite != User.Identity.Name)
                       {<a asp-controller="ChargerLocations"  asp-action="AddFavorite" asp-route-id="@charger.Id" > <button id="updatebutton" type="button" class="btn btn-success">Add to Favorites</button></a>
                           
                       } 
                    </div>
                </div>
            }
        </ul>
        
    </div>



        
        
    </div>
    


<script src = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBxinbaf5oXt9Jjy_gpqbXbsPfI-fQBztY" async defer></script>
<script src = "path/to/map.js"></script>